import os
import shutil
import pathlib
import pytest


@pytest.fixture(scope="session")
def input_directory():
    return pathlib.Path(__file__).parent / "input_files"


@pytest.fixture(scope="session")
def data_directory():
    return pathlib.Path(__file__).parent / "data"


@pytest.fixture(scope="session")
def test_env(tmp_path_factory, data_directory):
    """
    Copy the expensive/shared input data once per test session.
    """
    root = tmp_path_factory.mktemp("helena_env")
    shutil.copytree(data_directory, root / "data")
    return root


@pytest.fixture
def work_env(tmp_path, test_env):
    """
    Give each test its own isolated copy of the seeded environment.
    """
    workdir = tmp_path / "work"
    shutil.copytree(test_env / "data", workdir / "data")
    return workdir


@pytest.fixture
def run_in_tmp_dir(work_env, monkeypatch):
    """
    Temporarily change the directory to the working directory.
    """
    monkeypatch.chdir(work_env)


@pytest.fixture
def long_header():
    return [
        "Radius",
        "Height",
        "SIGMA",
        "EAMB-R",
        "EAMB-Z",
        "EF-TOT",
        "TE",
        "COLF",
        "PRESSURE",
        "AR3S",
        "AR4SM",
        "AR4SR",
        "AR4SPM",
        "AR4SPR",
        "AR4P",
        "AR4D",
        "AR+",
        "AR2*",
        "AR2+",
        "O2",
        "O2V",
        "O2*",
        "O2*1S",
        "O2+",
        "O",
        "O*",
        "O1S",
        "O+",
        "O-",
        "BE",
        "BE1",
        "BE2",
        "BE3",
        "BE4",
        "BE5",
        "BE6",
        "BE7",
        "BE8",
        "BE9",
        "BE+",
        "E",
        "E-SOURCE",
        "S-AR3S",
        "SEB-AR3S",
        "S-AR4SM",
        "SEB-AR4SM",
        "S-AR4SR",
        "SEB-AR4SR",
        "S-AR4SPM",
        "SEB-AR4SPM",
        "S-AR4SPR",
        "SEB-AR4SPR",
        "S-AR4P",
        "SEB-AR4P",
        "S-AR4D",
        "SEB-AR4D",
        "S-AR+",
        "SEB-AR+",
        "S-AR2*",
        "SEB-AR2*",
        "S-AR2+",
        "SEB-AR2+",
        "S-O2",
        "SEB-O2",
        "S-O2V",
        "SEB-O2V",
        "S-O2*",
        "SEB-O2*",
        "S-O2*1S",
        "SEB-O2*1S",
        "S-O2+",
        "SEB-O2+",
        "S-O",
        "SEB-O",
        "S-O*",
        "SEB-O*",
        "S-O1S",
        "SEB-O1S",
        "S-O+",
        "SEB-O+",
        "S-O-",
        "SEB-O-",
        "S-BE",
        "SEB-BE",
        "S-BE1",
        "SEB-BE1",
        "S-BE2",
        "SEB-BE2",
        "S-BE3",
        "SEB-BE3",
        "S-BE4",
        "SEB-BE4",
        "S-BE5",
        "SEB-BE5",
        "S-BE6",
        "SEB-BE6",
        "S-BE7",
        "SEB-BE7",
        "S-BE8",
        "SEB-BE8",
        "S-BE9",
        "SEB-BE9",
        "S-BE+",
        "SEB-BE+",
        "S-E",
        "SEB-E",
        "EB-ESORC",
        "POW-TOT",
        "POW-RF",
        "POW-RF-E",
        "P-POT",
        "RHO",
        "E FLUX-Z",
        "E FLUX-R",
        "VR-NEUTRAL",
        "VZ-NEUTRAL",
        "VR-ION+",
        "VZ-ION+",
        "VR-ION-",
        "VZ-ION-",
        "FZ-AR3S",
        "FR-AR3S",
        "FZ-AR4SM",
        "FR-AR4SM",
        "FZ-AR4SR",
        "FR-AR4SR",
        "FZ-AR4SPM",
        "FR-AR4SPM",
        "FZ-AR4SPR",
        "FR-AR4SPR",
        "FZ-AR4P",
        "FR-AR4P",
        "FZ-AR4D",
        "FR-AR4D",
        "FZ-AR+",
        "FR-AR+",
        "FZ-AR2*",
        "FR-AR2*",
        "FZ-AR2+",
        "FR-AR2+",
        "FZ-O2",
        "FR-O2",
        "FZ-O2V",
        "FR-O2V",
        "FZ-O2*",
        "FR-O2*",
        "FZ-O2*1S",
        "FR-O2*1S",
        "FZ-O2+",
        "FR-O2+",
        "FZ-O",
        "FR-O",
        "FZ-O*",
        "FR-O*",
        "FZ-O1S",
        "FR-O1S",
        "FZ-O+",
        "FR-O+",
        "FZ-O-",
        "FR-O-",
        "FZ-BE",
        "FR-BE",
        "FZ-BE1",
        "FR-BE1",
        "FZ-BE2",
        "FR-BE2",
        "FZ-BE3",
        "FR-BE3",
        "FZ-BE4",
        "FR-BE4",
        "FZ-BE5",
        "FR-BE5",
        "FZ-BE6",
        "FR-BE6",
        "FZ-BE7",
        "FR-BE7",
        "FZ-BE8",
        "FR-BE8",
        "FZ-BE9",
        "FR-BE9",
        "FZ-BE+",
        "FR-BE+",
        "JZ-NET",
        "JR-NET",
        "T-AR+",
        "T-AR2+",
        "T-O2+",
        "T-O+",
        "T-O-",
        "T-BE+",
        "T-AR3S",
        "T-AR4SM",
        "T-AR4SR",
        "T-AR4SPM",
        "T-AR4SPR",
        "T-AR4P",
        "T-AR4D",
        "T-AR2*",
        "T-O2",
        "T-O2V",
        "T-O2*",
        "T-O2*1S",
        "T-O",
        "T-O*",
        "T-O1S",
        "T-BE",
        "T-BE1",
        "T-BE2",
        "T-BE3",
        "T-BE4",
        "T-BE5",
        "T-BE6",
        "T-BE7",
        "T-BE8",
        "T-BE9",
        "TG-AVE",
        "I MFLUX-R",
        "I MFLUX-Z",
        "ION-TOT",
    ]


@pytest.fixture
def long_profile():
    return [
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
        0.0,
        10.17,
        8.136,
        6.102,
        4.068,
        2.034,
    ]
